name: river_reacher

channels:
  - esri
  - conda-forge

dependencies:
  - arcgis
  - cookiecutter
  - dask
  - jupyterlab
  - munch
  - nodejs
  - pip
  - pyarrow
  - pytest
  - python=3.9
  - python-dotenv
  - pyarrow
  - requests
  - scipy
  - scikit-learn
  - seaborn
  - shapely
  - swifter
  - pip:
    - bump2version
    - ipykernel
    - nbsphinx
    - sphinx
    - sphinx-autodoc-typehints
    - sphinx-copybutton
    - tox
    - tox-conda
    - twine
    - xmltodict
